#!/bin/bash

WS=pioneer_ws
PKG=alexa_helper_gui
PROJECT=gui
FILE_NAME=Listener
PATH_TO_PROJECT=~/indigo/$WS/src/$PKG/$PROJECT
PROJECT_CLASS_PATH=com.github.rosjava.alexa_gui_updated.$PROJECT.$FILE_NAME

$PATH_TO_PROJECT/build/install/$PROJECT/bin/$PROJECT $PROJECT_CLASS_PATH
